##########################################
# Makefile for MTV230 Device Drivers.
##########################################
ccflags-y += -Idrivers/media/isdbt
ccflags-y += -Idrivers/media/isdbt/mtv23x

obj-y += mtv23x.o
obj-y += mtv23x_demod.o
obj-y += mtv23x_rf.o
obj-y += mtv23x_port.o

